version: '3.8'

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "80:80"  # 호스트 포트 8080을 컨테이너 포트 80에 매핑
    environment:
      - SPRING_DATASOURCE_URL=jdbc:log4jdbc:oracle:thin:@oracle_db:1521/xepdb1
      - SPRING_DATASOURCE_USERNAME=sesac_highend
      - SPRING_DATASOURCE_PASSWORD=h12345d
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
      - oracle_db

  redis:
    image: redis:latest
    container_name: redis-server
    # CI 환경에서는 포트 매핑이 필요 없으므로 주석 처리
    # ports:
    #   - "6379:6379"

  oracle_db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=h12345d          # Oracle 비밀번호 설정
      - ORACLE_PDB=xepdb1                # PDB(Pluggable Database) 이름 설정
      - ORACLE_DATABASE=xepdb1           # 데이터베이스 이름 설정
    # CI 환경에서는 포트 매핑이 필요 없으므로 주석 처리
    # ports:
    #   - "1521:1521"
