server:
  port: 80  # 기본 포트 설정 (필요 시 변경 가능)

spring:
  datasource:
    url: jdbc:log4jdbc:oracle:thin:@oracle-db:1521/xepdb1
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sesac_highend
    password: h12345d

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: redis
    port: 6379

  security:
    user:
      name: highend
      password: h12345d
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
