server:
  port: 80  # Docker Compose에서 호스트 포트 8080으로 매핑됨

spring:
  application:
    name: shop

  datasource:
    url: jdbc:log4jdbc:oracle:thin:@xci.iptime.org:1521/xepdb1  # 'oracle-db'는 Docker Compose 서비스 이름
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sesac_highend
    password: h12345d

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

  thymeleaf:
    cache: false

  redis:
    host: redis  # 'redis'는 Docker Compose 서비스 이름
    port: 6379

  security:
    user:
      name: highend
      password: h12345d
    enabled: false  # Spring Security 비활성화 (필요 시 활성화)

management:
  endpoints:
    web:
      exposure:
        include: health, info  # health와 info 엔드포인트 노출
  endpoint:
    health:
      show-details: always  # 상세 헬스 정보 표시

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
