# src/main/resources/application-prod.yml

server:
  port: 80  # 프로덕션 환경에서 사용할 포트

spring:
  application:
    name: shop

  datasource:
    url: jdbc:log4jdbc:oracle:thin:@oracle-db:1521/xepdb1
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sesac_highend
    password: h12345d

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

  thymeleaf:
    cache: false

  redis:
    host: redis
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
