name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker Image
        run: docker build -t springboot-app .

      - name: Run Docker Container
        run: docker run -d -p 8080:80 --name springboot-app springboot-app

      - name: Wait for Application to Start
        run: |
          for i in {1..30}; do
            nc -z localhost 8080 && break
            echo "Waiting for application to start..."
            sleep 1
          done

      - name: Test Docker Container
        run: |
          # 애플리케이션이 호스트 포트 8080에서 실행 중인지 확인 (인증 포함)
          curl --fail --user highend:h12345d http://localhost:8080 || exit 1
